---
title: "R docker files for Data Science"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

This project is a collection of dockerfiles that can be used for data science. They are based on the awesome rocker project, and simply add addtional useful R packages and their dependencies. These files are build to images which are in turn housed on dockerhub.com. They can be pulled using the following command:

`docker pull joxborrow/sopimage:<tag>`

## Available Tags

### 3.4.4

This is the first image and is based on the rocker/tidyverse image. It is best characterized as a collection of the tidyverse and other useful packages. It currently includes the following extra packages (plus their dependencies).

### 3.6.2

### 3.6.3

<center>
| Group | Package |
|-------|---------|
|Data|assertr |  
|Data|pivottabler|
|Data|basictabler|
|Data|pdftools|
|Data|inspectdf|
|Data|naniar|
|Database|RSQLite|
|Database|RPostgreSQL|
|Database|RODBC|
|Database|RODBCDBI|
|Forecast & Time Series|fable|
|Forecast & Time Series|tsibble|
|Forecast & Time Series|feasts|
|Forecast & Time Series|forecast|
|Forecast & Time Series|MAPA|
|Forecast & Time Series|tsintermittent|
|Forecast & Time Series|hts|
|Forecast & Time Series|seasonal|
|Forecast & Time Series|tidyquant|
|Parallel Processing|foreach|
|Parallel Processing|doSNOW|
|Networks & Graphs|igraph|
|Networks & Graphs|DiagrammeR|
|Miscellaneaous|blastula|
|Miscellaneaous|BiocManager|
|Miscellaneaous|magick|
|Miscellaneaous|rsvg|
|HTML|shiny|
|HTML|shinythemes|
|HTML|shinyWidgets|
|HTML|flexdashboard|
|HTML|ggiraph|
|HTML|plotly|
|HTML|rpivotTable|
|ggplot|patchwork|
|ggplot|ggthemes|
|ggplot|tweenr|
|ggplot|gganimate|
|ggplot|ggalt|
|ggplot|ggrepel|
|ggplot|ggraph|
|ggplot|ggfortify|
|ggplot|ggtext|
|MS Office|flextable|
|MS Office|officer|
|MS Office|rvg|
|MS Office|mschart|
|MS Office|openxlsx|
</center>
